### ISSUE TITLE
Constantly have to re-enter keychain password, part 3

### ISSUE THREAD

**Issue by Gowiem** [99designs/aws-vault#534]
# TODOs
- [x] I am using the latest release of AWS Vault'
- I'm on v5.3.2
- [x] I have provided my `.aws/config` (redacted if necessary)
  - Can provide if needed.
- [x] I have provided the debug output using `aws-vault --debug` (redacted if necessary)
  - Can provide if needed. 

# Info
Following up on #219. I believe myself and others are still experiencing this issue. It sounds as if there is an ability to work around it, but it is not documented? I'm creating this issue so it is continued to be surfaced that a workaround or fix is still desired. 

I've tried the one workaround mentioned in #219 with using `export AWS_VAULT_KEYCHAIN_NAME=login`, but that just causes `aws-vault exec *` to spit out the following:

```
aws-vault: error: exec: Error getting temporary credentials: profile OMITTED: credentials missing
```

Any suggestions here? Happy to make a documentation update once I understand what need to be done so I don't need to enter my long password constantly 😅

**Comment by mtibben** [comment]
> Can provide if needed

please do provide!

**Comment by Gowiem** [comment]
@mtibben Gotcha, no problem. 

*Issue*: My personal issue is that I need to type in my aws-vault keyvault password every 5 (maybe 10?) or so minutes to run `aws-vault` commands. I just recently installed yesterday, got all my profiles setup, and started using the tool. On first use, I was prompted for my password twice, once with a "always allow" button which I selected, and then again a second time. On each subsequent use after that I am again prompted every 5 or minutes for my password to use the command. This would be fine if it was a longer session that was being created, but it's just painful with how short it is. 

`~/.aws/config`:
```
[default]
output=json
region=us-east-1

# ... 5 other, empty profiles

[profile made-up-name]
region=us-west-2
```

Here is some `aws-vault --debug` output where the first command I'm trying to use the workaround mentioned in #211 and the second command I'm using the default setup. I was prompted for my password on the second `aws-vault` command since I hadn't used `aws-vault` within the last 10 minutes. 
```
» export AWS_VAULT_KEYCHAIN_NAME=login                                                                                                      [py: v3.5.9] [node: v12.14.0] [ruby: v2.6.3] gowiem@GowieBookPro2
» av --debug exec made-up-name -- aws s3 ls                                                                                                 [py: v3.5.9] [node: v12.14.0] [ruby: v2.6.3] gowiem@GowieBookPro2
2020/02/26 19:40:16 aws-vault v5.3.2
2020/02/26 19:40:16 [keyring] Considering backends: [keychain pass file]
2020/02/26 19:40:16 Loading config file /Users/gowiem/.aws/config
2020/02/26 19:40:16 Parsing config file /Users/gowiem/.aws/config
2020/02/26 19:40:16 Using a session duration of "4h0m0s" from AWS_SESSION_TOKEN_TTL
2020/02/26 19:40:16 [keyring] Querying keychain for service="aws-vault", keychain="login.keychain"
2020/02/26 19:40:16 [keyring] Found 0 results
aws-vault: error: exec: Error getting temporary credentials: profile made-up-name: credentials missing
» atom ~/.aws/config                                                                                                                        [py: v3.5.9] [node: v12.14.0] [ruby: v2.6.3] gowiem@GowieBookPro2
» unset AWS_VAULT_KEYCHAIN_NAME                                                                                                             [py: v3.5.9] [node: v12.14.0] [ruby: v2.6.3] gowiem@GowieBookPro2
» av --debug exec made-up-name -- aws s3 ls                                                                                                 [py: v3.5.9] [node: v12.14.0] [ruby: v2.6.3] gowiem@GowieBookPro2
2020/02/26 19:47:20 aws-vault v5.3.2
2020/02/26 19:47:20 [keyring] Considering backends: [keychain pass file]
2020/02/26 19:47:20 Loading config file /Users/gowiem/.aws/config
2020/02/26 19:47:20 Parsing config file /Users/gowiem/.aws/config
2020/02/26 19:47:20 Using a session duration of "4h0m0s" from AWS_SESSION_TOKEN_TTL
2020/02/26 19:47:20 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/02/26 19:47:20 [keyring] Found 8 results
2020/02/26 19:47:20 profile made-up-name: using stored credentials
2020/02/26 19:47:20 profile made-up-name: using GetSessionToken
2020/02/26 19:47:20 Looking for sessions for made-up-name
2020/02/26 19:47:20 Looking up all keys in keyring
2020/02/26 19:47:20 [keyring] Querying keychain for service="aws-vault", keychain="aws-vault.keychain"
2020/02/26 19:47:20 [keyring] Found 8 results
2020/02/26 19:47:20 Session "session,bmstdGVycmFmb3Jt,,1582757545" expires in -3h54m55.573186s
2020/02/26 19:47:20 Session session,bmstdGVycmFmb3Jt,,1582757545 is expired, deleting
2020/02/26 19:47:20 [keyring] Removing keychain item service="aws-vault", account="session,bmstdGVycmFmb3Jt,,1582757545", keychain "aws-vault.keychain"
2020/02/26 19:47:44 Looking up keyring for 'pmade-up-name'
2020/02/26 19:47:44 [keyring] Querying keychain for service="aws-vault", account="pmade-up-name", keychain="aws-vault.keychain"
2020/02/26 19:47:49 [keyring] Found item "aws-vault (pmade-up-name)"
2020/02/26 19:47:50 Generated credentials ****************ZE5K using GetSessionToken, expires in 3h59m58.821249s
2020/02/26 19:47:50 Writing session for made-up-name to keyring: "session,bmstdGVycmFmb3Jt,,1582786069"
2020/02/26 19:47:50 [keyring] Checking keychain status
2020/02/26 19:47:50 [keyring] Keychain status returned nil, keychain exists
2020/02/26 19:47:50 [keyring] Keychain item trusts keyring
2020/02/26 19:47:50 [keyring] Adding service="aws-vault", label="aws-vault session for made-up-name", account="session,bmstdGVycmFmb3Jt,,1582786069", trusted=true to osx keychain "aws-vault.keychain"
2020/02/26 19:47:50 Setting subprocess env: AWS_DEFAULT_REGION=us-west-2, AWS_REGION=us-west-2
2020/02/26 19:47:50 Setting subprocess env: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
2020/02/26 19:47:50 Setting subprocess env: AWS_SESSION_TOKEN, AWS_SECURITY_TOKEN
2020/02/26 19:47:50 Setting subprocess env: AWS_SESSION_EXPIRATION
ACCOUNT S3 BUCKETS REDACTED
```

Please let me know if you need any more info.

**Comment by z0ph** [comment]
Hi,

I've always this issue on a brand new installation, but It's the normal behavior. (not a bug, a feature :))

To fix it: 
1. Open Keychain on macOS
2. Open the aws-vault keychain
3. Right clic on aws-vault keychain with change settings
4. Change the default lock timer.

![image](https://user-images.githubusercontent.com/20846187/76225957-7bdee400-621d-11ea-91a2-07c28bdb12bf.png)

Its very annoying :)

**Comment by Gowiem** [comment]
@z0ph Good stuff! I just tested that and that's exactly what I was looking for. That should definitely be in the README for others. I will submit a PR for updating with your instructions. Thanks!

cc @mtibben

**Comment by Gowiem** [comment]
Posted PR #540 to document this for others going forward.

**Comment by seh** [comment]
>     1. Open Keychain on macOS
>     2. Open the aws-vault keychain

Assuming you mean the _Keychain Access_ program, when I run it, I don't see an entry for _aws-vault_, and can't find anything with a name involving "aws" or "vault." Why is that?

**Comment by z0ph** [comment]
Sometimes, the `aws-vault` keychain is not present in the left panel of `Keychain Access` app, you need to go to :
- File -> Add Keychain (in Keychain Access App) and select the `aws-vault.keychain-db`

Usually, its created in `Users/{USER}/Library/Keychains`

**Comment by seh** [comment]
Thank you, @z0ph. That worked just as you described.

**Comment by morkot** [comment]
hey guys, just found this [blog post](https://www.decodednode.com/2021/05/aws-vault-on-macos-catalina.html) that describes how to configure keychain via cli tool ```security```

**Comment by xvierd** [comment]
> hey guys, just found this [blog post](https://www.decodednode.com/2021/05/aws-vault-on-macos-catalina.html) that describes how to configure keychain via cli tool `security`

Nice Thanks! also if for some reason you can't find the `Library/Keychains` remember this directory is hidden.

**Comment by TheodoreMelissa** [comment]
I was both lucky and able to have my funds retrieved with the help of Peter and his team from KEYCHEINX recovery company.
I want to share my story of how I became homeless and a victim of a cryptocurrency and romance scam that went on for several months before KeycheinX a team of cyber wizard came to my life. I was swindled of everything I have ever owned and went into depression. I am sure we all know $530k is no joke. At first, I thought all hope was lost until I came across an article about KeycheinX recovery service and how they can help me recover all that I lost. In short, KeycheinX recovery service was able to recover everything that i have lost to the hands of scammers after hacking into their server they recover more that the amount i invested. Being honest, their hacking prowess can not be matched and i still truly appreciate them till date. You can also contact them too if you’ve had a similar encounter in the past. Telegram: + 1 (415) 727 - 98 80 you can also reach out to them on email KeycheinX(@)mail. com

**Comment by filippovitale** [comment]
If you want to increase the timeout:

```
❯ security show-keychain-info ~/Library/Keychains/aws-vault.keychain-db
Keychain "/Users/fvitale/Library/Keychains/aws-vault.keychain-db" lock-on-sleep timeout=300s

❯ security set-keychain-settings -t 28800 ~/Library/Keychains/aws-vault.keychain-db

❯ security show-keychain-info ~/Library/Keychains/aws-vault.keychain-db
Keychain "/Users/fvitale/Library/Keychains/aws-vault.keychain-db" timeout=28800s
```

To change / remove password:

```
❯ security set-keychain-password ~/Library/Keychains/aws-vault.keychain-db
Old Password:
New Password:
Retype New Password:
```
